name: WS SBOM report generator - Master
on:
  push:
    branches:
      - '**'
#      - 'master'
    tags:
      - '*'
  schedule:
    - cron: '0 4 * * 6'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: UnicornGlobal/trufflehog-actions-scan@master
        with:
          branch: ${{ github.head_ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pyinstaller spdx-tools
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --ignore=E501,F841
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Create Standalone executable
        run: pyinstaller --onefile ./gitlab_integration/ws2gl_format_convertor.py
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: ws2gl_format_convertor
#          path: dist/ws2gl_format_convertor
      - name: Full test (License)
        run: python gitlab_integration/ws2gl_format_convertor.py -u ${{ secrets.WS_USER_KEY }} -k ${{ secrets.WS_SCOPE_PROJ_ZENBOT }} -t license
      - name: Full test (Security Violance)
        run: python gitlab_integration/ws2gl_format_convertor.py -u ${{ secrets.WS_USER_KEY }} -k ${{ secrets.WS_SCOPE_PROJ_ZENBOT }} -t security -o /tmp
      - name: Create Release
#        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifacts: dist/ws2gl_format_convertor
